image: node:10.15.3

pipelines:
  default:
      - step:
          name: Build and Test
          script:
          - echo "desplegando Branch development"
  branches:
    development:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install
              #- npm test
              - node --version
              - npm --version
              - CI=false npm run build
              - apt-get update
            artifacts:
              - build/**
        - step:
            name: Security Scan
            script:
            - echo "deploy whitout security scan"
           #   - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          clone:
            enabled: false
          script:
            # sync your files to S3
            - pipe: atlassian/aws-s3-deploy:0.4.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: 'build'
            # triggering a distribution invalidation to refresh the CDN caches
            - pipe: atlassian/aws-cloudfront-invalidate:0.1.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                DISTRIBUTION_ID: 'E3TC1EEJ72OJX8'    
