export const authConstants = {
  LOAD: 'AUTH_LOAD_DATA',
  CLEAN_ERROR: 'AUTH_CLEAN_ERROR',

  AUTH_REQUEST: 'AUTH_REQUEST',
  AUTH_FAILURE: 'AUTH_FAILURE',

  DATA_SUCCESS: 'AUTH_DATA_SUCCESS',
  DATA_FAILURE: 'AUTH_DATA_FAILURE',


  LOGOUT: 'AUTH_LOGOUT',

  SHOW_DIALOG: 'SHOW_DIALOG_CONFIRMED_PASSWORD',


  CURRENT_USER_REQUEST: 'AUTH_CURRENT_USER_REQUEST',
  CURRENT_USER_FAILURE: 'AUTH_CURRENT_USER_FAILURE',
  CURRENT_USER_SUCCESS: 'AUTH_CURRENT_USER_SUCCESS',

  GET_SESSION_REQUEST: 'AUTH_GET_SESSION_REQUEST',
  GET_SESSION_FAILURE: 'AUTH_GET_SESSION_FAILURE',
  GET_SESSION_SUCCESS: 'AUTH_GET_SESSION_SUCCESS',

  GET_DATA_REQUEST: 'AUTH_GET_DATA_REQUEST',
  GET_DATA_FAILURE: 'AUTH_GET_DATA_FAILURE',
  GET_DATA_SUCCESS: 'AUTH_GET_DATA_SUCCESS',
};
