export const benefitConstants = {
  LOAD: 'BENEFIT_REGISTER_LOAD_DATA',

  OFF_SUCCESS: 'LOAD_ORDER_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'BENEFIT_LIST_REQUEST',
  LIST_SUCCESS: 'BENEFIT_LIST_SUCCESS',
  LIST_FAILURE: 'BENEFIT_LIST_FAILURE',

  GETBYID_REQUEST: 'BENEFIT_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'BENEFIT_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'BENEFIT_GETBYID_FAILURE',

  REGISTER_REQUEST: 'BENEFIT_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'BENEFIT_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'BENEFIT_REGISTER_FAILURE',

  UPDATE_REQUEST: 'BENEFIT_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'BENEFIT_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'BENEFIT_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'BENEFIT_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'BENEFIT_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'BENEFIT_ACTIVATE_DEACTIVATE_FAILURE',
};
