export const boardingModeConstants = {
  LOAD: 'BOARDING_MODE_LOAD_DATA',

  OFF_SUCCESS: 'BOARDING_MODE_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'BOARDING_MODE_LIST_REQUEST',
  LIST_SUCCESS: 'BOARDING_MODE_LIST_SUCCESS',
  LIST_FAILURE: 'BOARDING_MODE_LIST_FAILURE',

  GETBYID_REQUEST: 'BOARDING_MODE_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'BOARDING_MODE_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'BOARDING_MODE_GETBYID_FAILURE',

  REGISTER_REQUEST: 'BOARDING_MODE_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'BOARDING_MODE_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'BOARDING_MODE_REGISTER_FAILURE',

  UPDATE_REQUEST: 'BOARDING_MODE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'BOARDING_MODE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'BOARDING_MODE_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'BOARDING_MODE_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'BOARDING_MODE_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'BOARDING_MODE_ACTIVATE_DEACTIVATE_FAILURE',
};
