export const brandConstants = {
  LOAD: 'BRAND_LOAD_DATA',

  OFF_SUCCESS: 'BRAND_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'BRAND_LIST_REQUEST',
  LIST_SUCCESS: 'BRAND_LIST_SUCCESS',
  LIST_FAILURE: 'BRAND_LIST_FAILURE',

  GETBYID_REQUEST: 'BRAND_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'BRAND_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'BRAND_GETBYID_FAILURE',

  REGISTER_REQUEST: 'BRAND_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'BRAND_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'BRAND_REGISTER_FAILURE',

  UPDATE_REQUEST: 'BRAND_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'BRAND_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'BRAND_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'BRAND_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'BRAND_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'BRAND_ACTIVATE_DEACTIVATE_FAILURE',
};
