export const categoryConstants = {
  LOAD: 'CATEGORY_LOAD_DATA',

  OFF_SUCCESS: 'CATEGORY_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'CATEGORY_LIST_REQUEST',
  LIST_SUCCESS: 'CATEGORY_LIST_SUCCESS',
  LIST_FAILURE: 'CATEGORY_LIST_FAILURE',

  GETBYID_REQUEST: 'CATEGORY_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'CATEGORY_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'CATEGORY_GETBYID_FAILURE',

  REGISTER_REQUEST: 'CATEGORY_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'CATEGORY_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'CATEGORY_REGISTER_FAILURE',

  UPDATE_REQUEST: 'CATEGORY_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'CATEGORY_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'CATEGORY_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'CATEGORY_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'CATEGORY_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'CATEGORY_ACTIVATE_DEACTIVATE_FAILURE',
};
