export const cityConstants = {
  LOAD: 'CITY_LOAD_DATA',

  OFF_SUCCESS: 'CITY_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'CITY_LIST_REQUEST',
  LIST_SUCCESS: 'CITY_LIST_SUCCESS',
  LIST_FAILURE: 'CITY_LIST_FAILURE',

  GETBYID_REQUEST: 'CITY_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'CITY_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'CITY_GETBYID_FAILURE',

  REGISTER_REQUEST: 'CITY_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'CITY_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'CITY_REGISTER_FAILURE',

  UPDATE_REQUEST: 'CITY_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'CITY_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'CITY_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'CITY_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'CITY_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'CITY_ACTIVATE_DEACTIVATE_FAILURE',
};
