export const clientConstants = {
  LOAD: 'CLIENT_REGISTER_LOAD_DATA',

  LIST_REQUEST: 'CLIENT_LIST_REQUEST',
  LIST_SUCCESS: 'CLIENT_LIST_SUCCESS',
  LIST_FAILURE: 'CLIENT_LIST_FAILURE',

  REGISTER_REQUEST: 'CLIENT_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'CLIENT_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'CLIENT_REGISTER_FAILURE',
};
