export const companyConstants = {
  LOAD: 'COMPANY_REGISTER_LOAD_DATA',

  OFF_SUCCESS: 'LOAD_ORDER_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'COMPANY_LIST_REQUEST',
  LIST_SUCCESS: 'COMPANY_LIST_SUCCESS',
  LIST_FAILURE: 'COMPANY_LIST_FAILURE',

  GETBYID_REQUEST: 'COMPANY_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'COMPANY_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'COMPANY_GETBYID_FAILURE',

  REGISTER_REQUEST: 'COMPANY_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'COMPANY_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'COMPANY_REGISTER_FAILURE',

  UPDATE_REQUEST: 'COMPANY_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'COMPANY_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'COMPANY_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'COMPANY_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'COMPANY_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'COMPANY_ACTIVATE_DEACTIVATE_FAILURE',
};
