export const dispatchTypeConstants = {
  LOAD: 'DISPATCH_TYPE_LOAD_DATA',

  OFF_SUCCESS: 'DISPATCH_TYPE_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'DISPATCH_TYPE_LIST_REQUEST',
  LIST_SUCCESS: 'DISPATCH_TYPE_LIST_SUCCESS',
  LIST_FAILURE: 'DISPATCH_TYPE_LIST_FAILURE',

  GETBYID_REQUEST: 'DISPATCH_TYPE_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'DISPATCH_TYPE_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'DISPATCH_TYPE_GETBYID_FAILURE',

  REGISTER_REQUEST: 'DISPATCH_TYPE_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'DISPATCH_TYPE_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'DISPATCH_TYPE_REGISTER_FAILURE',

  UPDATE_REQUEST: 'DISPATCH_TYPE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'DISPATCH_TYPE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'DISPATCH_TYPE_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'TYPE_SERVICE_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'TYPE_SERVICE_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'TYPE_SERVICE_ACTIVATE_DEACTIVATE_FAILURE',
};
