export const featureConstants = {
  LOAD: 'FEATURE_REGISTER_LOAD_DATA',

  OFF_SUCCESS: 'LOAD_ORDER_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'FEATURE_LIST_REQUEST',
  LIST_SUCCESS: 'FEATURE_LIST_SUCCESS',
  LIST_FAILURE: 'FEATURE_LIST_FAILURE',

  GETBYID_REQUEST: 'FEATURE_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'FEATURE_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'FEATURE_GETBYID_FAILURE',

  REGISTER_REQUEST: 'FEATURE_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'FEATURE_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'FEATURE_REGISTER_FAILURE',

  UPDATE_REQUEST: 'FEATURE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'FEATURE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'FEATURE_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'FEATURE_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'FEATURE_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'FEATURE_ACTIVATE_DEACTIVATE_FAILURE',
};
