export const loadOrderConstants = {
  LOAD: 'TRAVEL_LOAD_DATA',
  OFF_SUCCESS: 'TRAVEL_OFF_LOAD_SUCCESS',

  LOAD_REQUEST: 'TRAVEL_LOAD_REQUEST',
  LOAD_SUCCESS: 'TRAVEL_LOAD_SUCCESS',
  LOAD_FAILURE: 'TRAVEL_LOAD_FAILURE',

  LIST_REQUEST: 'TRAVEL_LIST_REQUEST',
  LIST_SUCCESS: 'TRAVEL_LIST_SUCCESS',
  LIST_FAILURE: 'TRAVEL_LIST_FAILURE',

  GETBYID_REQUEST: 'TRAVEL_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'TRAVEL_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'TRAVEL_GETBYID_FAILURE',

  REGISTER_REQUEST: 'TRAVEL_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'TRAVEL_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'TRAVEL_REGISTER_FAILURE',

  PUBLISH_REQUEST: 'TRAVEL_PUBLISH_REQUEST',
  PUBLISH_SUCCESS: 'TRAVEL_PUBLISH_SUCCESS',
  PUBLISH_FAILURE: 'TRAVEL_PUBLISH_FAILURE',

  LOADING_ORDER_CREATE_REQUEST: 'TRAVEL_LOADING_ORDER_CREATE_REQUEST',
  LOADING_ORDER_CREATE_SUCCESS: 'TRAVEL_LOADING_ORDER_CREATE_SUCCESS',
  LOADING_ORDER_CREATE_FAILURE: 'TRAVEL_LOADING_ORDER_CREATE_FAILURE',

  LIQUIDATE_REQUEST: 'TRAVEL_LIQUIDATE_REQUEST',
  LIQUIDATE_SUCCESS: 'TRAVEL_LIQUIDATE_SUCCESS',
  LIQUIDATE_FAILURE: 'TRAVEL_LIQUIDATE_FAILURE',

  CHECKPOINTS_REQUEST: 'TRAVEL_CHECKPOINTS_REQUEST',
  CHECKPOINTS_SUCCESS: 'TRAVEL_CHECKPOINTS_SUCCESS',
  CHECKPOINTS_FAILURE: 'TRAVEL_CHECKPOINTS_FAILURE',

  LOADING_ORDER_CREATE_DIRECT_REQUEST: 'TRAVEL_LOADING_ORDER_CREATE_DIRECT_REQUEST',
  LOADING_ORDER_CREATE_DIRECT_SUCCESS: 'TRAVEL_LOADING_ORDER_CREATE_DIRECT_SUCCESS',
  LOADING_ORDER_CREATE_DIRECT_FAILURE: 'TRAVEL_LOADING_ORDER_CREATE_DIRECT_FAILURE',
};
