
export const mapsConstants = {

GEOCODING_REQUEST: 'GEOCODING_REQUEST',
GEOCODING_SUCCESS: 'GEOCODING_SUCCESS',
GEOCODING_FAILURE: 'GEOCODING_FAILURE',

GEOFENCING_REQUEST: 'GEOFENCING_REQUEST',
GEOFENCING_SUCCESS: 'GEOFENCING_SUCCESS',
GEOFENCING_FAILURE: 'GEOFENCING_FAILURE'
}