export const moduleConstants = {
  LIST_REQUEST: 'MODULE_LIST_REQUEST',
  LIST_SUCCESS: 'MODULE_LIST_SUCCESS',
  LIST_FAILURE: 'MODULE_LIST_FAILURE',

  GETBYID_REQUEST: 'MODULE_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'MODULE_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'MODULE_GETBYID_FAILURE',

  CREATE: 'MODULE_CREATE',
  CREATE_BEGIN: 'MODULE_CREATE_BEGIN',
  CREATE_SUCCESS: 'MODULE_CREATE_SUCCESS',
  CREATE_FAILURE: 'MODULE_CREATE_FAILURE',

  UPDATE: 'MODULE_UPDATE',
  UPDATE_BEGIN: 'MODULE_UPDATE_BEGIN',
  UPDATE_SUCCESS: 'MODULE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'MODULE_UPDATE_FAILURE',
};
