export const newConstants = {
  LOAD: 'NEW_REGISTER_LOAD_DATA',

  OFF_SUCCESS: 'LOAD_ORDER_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'NEW_LIST_REQUEST',
  LIST_SUCCESS: 'NEW_LIST_SUCCESS',
  LIST_FAILURE: 'NEW_LIST_FAILURE',

  GETBYID_REQUEST: 'NEW_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'NEW_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'NEW_GETBYID_FAILURE',

  REGISTER_REQUEST: 'NEW_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'NEW_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'NEW_REGISTER_FAILURE',

  UPDATE_REQUEST: 'NEW_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'NEW_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'NEW_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'NEW_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'NEW_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'NEW_ACTIVATE_DEACTIVATE_FAILURE',
};
