export const notificationConstants = {
  NOTIFICATION_SHOW: 'NOTIFICATION_SHOW',

  ADD_REQUEST: 'NOTIFICATION_ADD_REQUEST',
  ADD_SUCCESS: 'NOTIFICATION_ADD_SUCCESS',
  ADD_FAILURE: 'NOTIFICATION_ADD_FAILURE',

  READ_REQUEST: 'NOTIFICATION_READ_REQUEST',
  READ_SUCCESS: 'NOTIFICATION_READ_SUCCESS',
  READ_FAILURE: 'NOTIFICATION_READ_FAILURE',

  TOKEN_REQUEST: 'NOTIFICATION_TOKEN_REQUEST',
  TOKEN_SUCCESS: 'NOTIFICATION_TOKEN_SUCCESS',
  TOKEN_FAILURE: 'NOTIFICATION_TOKEN_FAILURE',
};
