export const operationConstants = {
  LOAD: 'OPERATION_LOAD_DATA',
  OFF_SUCCESS: 'OPERATION_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'OPERATION_LIST_REQUEST',
  LIST_SUCCESS: 'OPERATION_LIST_SUCCESS',
  LIST_FAILURE: 'OPERATION_LIST_FAILURE',

  GETBYID_REQUEST: 'OPERATION_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'OPERATION_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'OPERATION_GETBYID_FAILURE',

  REGISTER_REQUEST: 'OPERATION_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'OPERATION_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'OPERATION_REGISTER_FAILURE',

  UPDATE_REQUEST: 'OPERATION_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'OPERATION_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'OPERATION_UPDATE_FAILURE',

  DASHBOARD_REQUEST: 'OPERATION_DASHBOARD_REQUEST',
  DASHBOARD_SUCCESS: 'OPERATION_DASHBOARD_SUCCESS',
  DASHBOARD_FAILURE: 'OPERATION_DASHBOARD_FAILURE',
};
