export const operationStatusConstants = {
  LOAD: 'OPERATION_STATUS_LOAD_DATA',

  LIST_REQUEST: 'OPERATION_STATUS_LIST_REQUEST',
  LIST_SUCCESS: 'OPERATION_STATUS_LIST_SUCCESS',
  LIST_FAILURE: 'OPERATION_STATUS_LIST_FAILURE',

  GETBYID_REQUEST: 'OPERATION_STATUS_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'OPERATION_STATUS_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'OPERATION_STATUS_GETBYID_FAILURE',

  REGISTER_REQUEST: 'OPERATION_STATUS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'OPERATION_STATUS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'OPERATION_STATUS_REGISTER_FAILURE',
};
