export const operatorConstants = {
  LOAD: 'OPERATOR_LOAD_DATA',
  OFF_SUCCESS: 'OPERATOR_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'OPERATOR_LIST_REQUEST',
  LIST_SUCCESS: 'OPERATOR_LIST_SUCCESS',
  LIST_FAILURE: 'OPERATOR_LIST_FAILURE',

  GETBYID_REQUEST: 'OPERATOR_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'OPERATOR_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'OPERATOR_GETBYID_FAILURE',

  REGISTER_REQUEST: 'OPERATOR_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'OPERATOR_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'OPERATOR_REGISTER_FAILURE',

  UPDATE_REQUEST: 'OPERATOR_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'OPERATOR_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'OPERATOR_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'OPERATOR_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'OPERATOR_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'OPERATOR_ACTIVATE_DEACTIVATE_FAILURE',
};
