export const placeConstants = {
  LOAD: 'PLACE_LOAD_DATA',
  OFF_SUCCESS: 'PLACE_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'PLACE_LIST_REQUEST',
  LIST_SUCCESS: 'PLACE_LIST_SUCCESS',
  LIST_FAILURE: 'PLACE_LIST_FAILURE',

  GETBYID_REQUEST: 'PLACE_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'PLACE_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'PLACE_GETBYID_FAILURE',

  REGISTER_REQUEST: 'PLACE_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'PLACE_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'PLACE_REGISTER_FAILURE',

  UPDATE_REQUEST: 'PLACE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PLACE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'PLACE_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'PLACE_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'PLACE_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'PLACE_ACTIVATE_DEACTIVATE_FAILURE',
};
