export const postulationConstants = {
  OFF_SUCCESS: 'POSTULATION_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'POSTULATION_LIST_REQUEST',
  LIST_SUCCESS: 'POSTULATION_LIST_SUCCESS',
  LIST_FAILURE: 'POSTULATION_LIST_FAILURE',

  ACCEPT_REQUEST: 'POSTULATION_ACCEPT_REQUEST',
  ACCEPT_SUCCESS: 'POSTULATION_ACCEPT_SUCCESS',
  ACCEPT_FAILURE: 'POSTULATION_ACCEPT_FAILURE',

  CONFIRMED_REQUEST: 'POSTULATION_CONFIRMED_GETBYTRAVEL_REQUEST',
  CONFIRMED_SUCCESS: 'POSTULATION_CONFIRMED_GETBYTRAVEL_SUCCESS',
  CONFIRMED_FAILURE: 'POSTULATION_CONFIRMED_GETBYTRAVEL_FAILURE',
};
