export const profileConstants = {
  LOAD: 'AUTH_LOAD_DATA',

  GETBYID_REQUEST: 'PROFILE_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'PROFILE_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'PROFILE_GETBYID_FAILURE',

  UPDATE: 'PROFILE_UPDATE',
  UPDATE_BEGIN: 'PROFILE_UPDATE_BEGIN',
  UPDATE_REQUEST: 'PROFILE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PROFILE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'PROFILE_UPDATE_FAILURE',
};
