export const routesConstants = {
    CREATE_REQUEST: 'ROUTE_CREATE_REQUEST',
    CREATE_SUCCESS: 'ROUTE_CREATE_SUCCESS',
    CREATE_FAILURE: 'ROUTE_CREATE_FAILURE',

    GETALL_REQUEST: 'ROUTE_GETALL_REQUEST',
    GETALL_SUCCESS: 'ROUTE_GETALL_SUCCESS',
    GETALL_FAILURE: 'ROUTE_GETALL_FAILURE',

    UPDATE_REQUEST: 'ROUTE_UPDATE_REQUEST',
    UPDATE_SUCCESS: 'ROUTE_UPDATE_SUCCESS',
    UPDATE_FAILURE: 'ROUTE_UPDATE_FAILURE',

    ACTIVATE_DEACTIVATE_REQUEST: 'ROUTE_ACTIVATE_DEACTIVATE_REQUEST',
    ACTIVATE_DEACTIVATE_SUCCESS: 'ROUTE_ACTIVATE_DEACTIVATE_SUCCESS',
    ACTIVATE_DEACTIVATE_FAILURE: 'ROUTE_ACTIVATE_DEACTIVATE_FAILURE',

    SELECT_ONE_REQUEST: 'ROUTE_SELECT_ONE',
  };