export const stagesTemplateConstants = {
  LOAD: 'STAGES_TEMPLATE_LOAD_DATA',

  OFF_SUCCESS: 'STAGES_TEMPLATE_OFF_LOAD_SUCCESS',

  LOAD_REQUEST: 'STAGES_TEMPLATE_LOAD_REQUEST',
  LOAD_SUCCESS: 'STAGES_TEMPLATE_LOAD_SUCCESS',
  LOAD_FAILURE: 'STAGES_TEMPLATE_LOAD_FAILURE',

  LIST_REQUEST: 'STAGES_TEMPLATE_LIST_REQUEST',
  LIST_SUCCESS: 'STAGES_TEMPLATE_LIST_SUCCESS',
  LIST_FAILURE: 'STAGES_TEMPLATE_LIST_FAILURE',

  /* one template stage by stageTemplateId */
  GETBYID_REQUEST: 'STAGES_TEMPLATE_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'STAGES_TEMPLATE_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'STAGES_TEMPLATE_GETBYID_FAILURE',

  /* all template stages by dispatchTypeId, typeServiceId y placeId */
  GETBYIDS_REQUEST: 'STAGES_TEMPLATE_GETBYIDS_REQUEST',
  GETBYIDS_SUCCESS: 'STAGES_TEMPLATE_GETBYIDS_SUCCESS',
  GETBYIDS_FAILURE: 'STAGES_TEMPLATE_GETBYIDS_FAILURE',

  REGISTER_REQUEST: 'STAGES_TEMPLATE_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'STAGES_TEMPLATE_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'STAGES_TEMPLATE_REGISTER_FAILURE',

  UPDATE_REQUEST: 'STAGES_TEMPLATE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'STAGES_TEMPLATE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'STAGES_TEMPLATE_UPDATE_FAILURE',

  DELETE_TASK_REQUEST: 'STAGES_TEMPLATE_DELETE_TASK_REQUEST',
  DELETE_TASK_SUCCESS: 'STAGES_TEMPLATE_DELETE_TASK_SUCCESS',
  DELETE_TASK_FAILURE: 'STAGES_TEMPLATE_DELETE_TASK_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'STAGES_TEMPLATE_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'STAGES_TEMPLATE_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'STAGES_TEMPLATE_ACTIVATE_DEACTIVATE_FAILURE',
};
