export const stageConstants = {
  REGISTER_REQUEST: 'STAGE_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'STAGE_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'STAGE_REGISTER_FAILURE',

  APPROVE_TASK_REQUEST: 'STAGE_APPROVE_TASK_REQUEST',
  APPROVE_TASK_SUCCESS: 'STAGE_APPROVE_TASK_SUCCESS',
  APPROVE_TASK_FAILURE: 'STAGE_APPROVE_TASK_FAILURE',

  GETTASK_BYIDS_REQUEST: 'STAGE_GETTASK_BYIDS_REQUEST',
  GETTASK_BYIDS_SUCCESS: 'STAGE_GETTASK_BYIDS_SUCCESS',
  GETTASK_BYIDS_FAILURE: 'STAGE_GETTASK_BYIDS_FAILURE',
};
