export const taskConstants = {
  LOAD: 'TASK_REGISTER_LOAD_DATA',

  OFF_SUCCESS: 'TYPE_SERVICE_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'TASK_LIST_REQUEST',
  LIST_SUCCESS: 'TASK_LIST_SUCCESS',
  LIST_FAILURE: 'TASK_LIST_FAILURE',

  GETBYID_REQUEST: 'TASK_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'TASK_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'TASK_GETBYID_FAILURE',

  REGISTER_REQUEST: 'TASK_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'TASK_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'TASK_REGISTER_FAILURE',

  UPDATE_REQUEST: 'TASK_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'TASK_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'TASK_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'TASK_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'TASK_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'TASK_ACTIVATE_DEACTIVATE_FAILURE',

  APPROVE_REQUEST: 'TASK_APPROVE_REQUEST',
  APPROVE_SUCCESS: 'TASK_APPROVE_SUCCESS',
  APPROVE_FAILURE: 'TASK_APPROVE_FAILURE',
};
