export const transportUnitConstants = {
  LOAD: 'TRANSPORT_UNIT_LOAD_DATA',

  /* LIST_REQUEST: 'TRANSPORT_UNIT_LIST_REQUEST',
  LIST_SUCCESS: 'TRANSPORT_UNIT_LIST_SUCCESS',
  LIST_FAILURE: 'TRANSPORT_UNIT_LIST_FAILURE', */

  GETBYID_REQUEST: 'TRANSPORT_UNIT_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'TRANSPORT_UNIT_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'TRANSPORT_UNIT_GETBYID_FAILURE',

  SEARCH_REQUEST: 'TRANSPORT_UNIT_SEARCH_REQUEST',
  SEARCH_SUCCESS: 'TRANSPORT_UNIT_SEARCH_SUCCESS',
  SEARCH_FAILURE: 'TRANSPORT_UNIT_SEARCH_FAILURE',
};
