export const typeTransportUnitConstants = {
  LOAD: 'TYPE_TRANSPORT_UNIT_LOAD_DATA',

  OFF_SUCCESS: 'TYPE_TRANSPORT_UNIT_OFF_LOAD_SUCCESS',

  LOAD_REQUEST: 'TYPE_TRANSPORT_UNIT_LOAD_REQUEST',
  LOAD_SUCCESS: 'TYPE_TRANSPORT_UNIT_LOAD_SUCCESS',
  LOAD_FAILURE: 'TYPE_TRANSPORT_UNIT_LOAD_FAILURE',

  LIST_REQUEST: 'TYPE_TRANSPORT_UNIT_LIST_REQUEST',
  LIST_SUCCESS: 'TYPE_TRANSPORT_UNIT_LIST_SUCCESS',
  LIST_FAILURE: 'TYPE_TRANSPORT_UNIT_LIST_FAILURE',

  GETBYID_REQUEST: 'TYPE_TRANSPORT_UNIT_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'TYPE_TRANSPORT_UNIT_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'TYPE_TRANSPORT_UNIT_GETBYID_FAILURE',

  REGISTER_REQUEST: 'TYPE_TRANSPORT_UNIT_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'TYPE_TRANSPORT_UNIT_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'TYPE_TRANSPORT_UNIT_REGISTER_FAILURE',

  UPDATE_REQUEST: 'TYPE_TRANSPORT_UNIT_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'TYPE_TRANSPORT_UNIT_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'TYPE_TRANSPORT_UNIT_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'TYPE_TRANSPORT_UNIT_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'TYPE_TRANSPORT_UNIT_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'TYPE_TRANSPORT_UNIT_ACTIVATE_DEACTIVATE_FAILURE',
};
