export const typeServiceConstants = {
  LOAD: 'TYPE_SERVICE_LOAD_DATA',

  OFF_SUCCESS: 'TYPE_SERVICE_OFF_LOAD_SUCCESS',

  LIST_REQUEST: 'TYPE_SERVICE_LIST_REQUEST',
  LIST_SUCCESS: 'TYPE_SERVICE_LIST_SUCCESS',
  LIST_FAILURE: 'TYPE_SERVICE_LIST_FAILURE',

  GETBYID_REQUEST: 'TYPE_SERVICE_GETBYID_REQUEST',
  GETBYID_SUCCESS: 'TYPE_SERVICE_GETBYID_SUCCESS',
  GETBYID_FAILURE: 'TYPE_SERVICE_GETBYID_FAILURE',

  REGISTER_REQUEST: 'TYPE_SERVICE_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'TYPE_SERVICE_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'TYPE_SERVICE_REGISTER_FAILURE',

  UPDATE_REQUEST: 'TYPE_SERVICE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'TYPE_SERVICE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'TYPE_SERVICE_UPDATE_FAILURE',

  ACTIVATE_DEACTIVATE_REQUEST: 'TYPE_SERVICE_ACTIVATE_DEACTIVATE_REQUEST',
  ACTIVATE_DEACTIVATE_SUCCESS: 'TYPE_SERVICE_ACTIVATE_DEACTIVATE_SUCCESS',
  ACTIVATE_DEACTIVATE_FAILURE: 'TYPE_SERVICE_ACTIVATE_DEACTIVATE_FAILURE',
};
